export enum LoginMethodEnum {
  GOOGLE_PROVIDER = 'GOOGLE_PROVIDER',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
  EMAIL_OTP_PROVIDER = 'EMAIL_OTP_PROVIDER',
  MOBILE_OTP_PROVIDER = 'MOBILE_OTP_PROVIDER',
}
